
#response when the Chatbot is uncertain
ErrorMsg=["I am Sorry! I don't understand. Please check your spelling and keywords. <br> Maybe these pathways can help: <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/admissioninfo/FeeInd.aspx'>Programs</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/About/Overview/Overview.aspx'>About Integral</a></button>  <button class = 'link__button' type='button'><a href='https://admission.iul.ac.in/'>Application Form</a></button> <button class = 'link__button' type = 'button'><a href=' https://iul.ac.in/AdmissionInfo/Vertual_Tour.aspx#target'>Virtual Campus Tour</a></button> <br> <br> For talking to an actual person, please call +919335177775","Sorry! I could not understand what you're trying to say. <br> Maybe these pathways can help: <br><button class = 'link__button' type = 'button'><a href='https://iul.ac.in/admissioninfo/FeeInd.aspx'>Programs</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/About/Overview/Overview.aspx'>About Integral</a></button>  <button class = 'link__button' type='button'><a href='https://admission.iul.ac.in/'>Application Form</a></button> <button class = 'link__button' type = 'button'><a href=' https://iul.ac.in/AdmissionInfo/Vertual_Tour.aspx#target'>Virtual Campus Tour</a></button> <br> <br> For talking to an actual person, please call +919335177775", "Sorry, I was not able to understand. Please rephrase your intention. <br> Maybe also these pathways can help: <br><br><button class = 'link__button' type = 'button'><a href='https://iul.ac.in/admissioninfo/FeeInd.aspx'>Programs</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/About/Overview/Overview.aspx'>About Integral</a></button>  <button class = 'link__button' type='button'><a href='https://admission.iul.ac.in/'>Application Form</a></button> <button class = 'link__button' type = 'button'><a href=' https://iul.ac.in/AdmissionInfo/Vertual_Tour.aspx#target'>Virtual Campus Tour</a></button> <br> <br> For talking to an actual person, please call +919335177775"]

# words which are valid as single user-input 
validOneWord =["hi", "hello", "bye", "great", "ok","nice", "okay", "no", "nope", "nothing", "programs", 'fees', 'fee','iuet', 'loan', 'scholarship', 'hey', 'thanks']



#keywords and its synonyms which induce a predefined response
course_inputs = (
            ["biomedical","biomed" ,"btechbe", "mtechbe","bbe", "mbe", "m.be", "b.be"],
            ["mechanical","btechmech", "mtechmech", "bmech", "mmech", "m.mech", "b.mech", "mech"],
            ["electrical","btechee", "mtechee", "bee", "mee", "m.ee", "b.ee"],
            ["civil", "btechce", "mtechce","bce", "cee", "m.ce", "b.ce", "ce"],
            ["computer", "btechcse", "mtechcse","bcse", "b.c.s.e","mcse", "m.cse", "b.cse","cse", "btechca", "mtechca","bca", "b.c.a.","mca", "m.ca", "b.ca"],
            ["food", "btechft", "mtechft","bft", "mft", "m.ft", "b.ft"],
            ["electronics","btechece", "mtechece","bece", "mece", "m.ece", "b.ece", "ece"],
            ["biotechnology", "biotech", "btechbt", "mtechbt","bbt", "mbt", "m.bt", "b.bt"],
            ["bioinformatics","btechbi", "mtechbi", "bbi", "mbi", "m.bi", "b.bi"],

            ['agriculture', 'bscagri', 'mscagri', 'agricultural', 'btechagri','b.techagri','agri', 'mbaagri'],

            ['physics', 'mathematics', 'maths', 'math'],
            ['industrial', 'chemistry', 'zoology', 'botany', 'biochem', 'biochemistry'],
            ['life'],
            ['environmental'], 

            ["architecture", "march", "barch", "b.arch","m.arch"],
            ["design", "bd", "b.d", 'bdes', 'b.des'],

            ['pharmacy', 'pharm.d.', 'pharmd', 'bpharm', 'mpharm', 'pharm'],

            ["commerce", "mcom", "bcom","b.com","m.com", "b.comm","m.comm"],
            ["business", "administration", "management","bba", "mba"],


            ['mbbs', 'm.b.b.s.', 'm.b.b.s'],
            ['physiotherapy', 'bpt', "mpt"],
            ['laboratory'],
            ['optometry'],
            ['radiological', 'radiology'],
            ['forensic'],
            ['ophthalmology'],
            ['pathology'],
            ['anesthesiology'],
            ['obstetrics' , 'gynaecology'],
            ['anatomy', 'ma', 'mscma'],
            ['microbiology', 'micro', 'mb', 'medmicro'],
            ['physiology', 'mp'],

            ['education', 'med', 'b.ed', 'm.ed'],

            ['english'],
            ['economics'],
            ['political'],
            ['psychology', 'psych', 'bpsych', 'b.psych'],

            ['law', 'blaw', "mbalaw", 'balaw', "ll.b.", "llb", "l.l.b.","b.a.ll.b", "ballb", "bba.ll.b", "bballb", "ll.m", "llm"],

            ['nursing', 'bn', 'nurse'],
     
            )

course_responses = [
                " <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechBiomedical.aspx'>B.Tech - Biomedical Engineering</a></button> <br><br> This site contains all general information about this course.<br><br> For possible career paths please type <b> biomed-career </b>",
                "I think I can help. <br> First, the following links give general information about our programs in <b>Mechanical Engineering</b>. <br><br> Secondly, <br> please type '<b>mech-career</b>' for information about career paths in this field. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechME.aspx'>B.Tech - Mech</a></button>  <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/PG/PG_Production_and_Industrial.aspx'>M.Tech - Mech</a></button>",
                "Okay. I'm glad to hear you're interested in our program in <b>Electrical Engineering</b>. Let me give you the general facts about the same. <br> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechEE.aspx'>B.Tech - EE</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2293'>M.Tech - EE</a></button> <br><br> Furthermore, please type '<b>ee-career</b>' for information about career paths in this field.",
                "Ah you're interested in our courses in <b>Civil Engineering</b>. Then I recommend you to check out the pages below.  <br><br> For possible career paths in this field please type <br>'<b>ce-career</b>' <br><br> <button class = 'link__button'  type = 'button'><a href='https://iul.ac.in/Program/UG/UG_BTechCivilEngineering.aspx'>B.Tech - CE</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2291'>M.Tech - CE</a></button>",
                "I think these links containing general overviews over the course will help. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2294'>B.Tech - CSE</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2292'>M.Tech - CSE</a></button> <br><br>  <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/UG/UG_BCA.aspx'>BCA</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/PG/PG_mca.aspx'>MCA</a></button> <br><br> Also I provide you facts about career paths when you type in '<b>cse-career</b>' or '<b>ca-career</b>'.",
                "I think these pages below with general information about our courses in <b>Food Technology</b> can be what you're searching for. <br><br><button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechFoodTechnology.aspx'>Bachelor</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_Foodtech.aspx'>Master</a></button> <br><br> By typing '<b>food-career</b>' I'll give you information about career paths in this field." ,
                "Okay. Below, by clicking on the buttons, you'll find some general information about our programs in <b>Electronics & Communication Engineering</b>. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechECE.aspx'>B.Tech - ECE</a></button> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/PG/M_Electronics_Communication.aspx'>M.Tech - ECE</a></button> <br><br> Check out the career paths by typing '<b>ece-career</b>' ",
                "Okay. Visit one of the following pages to get all general information about our programs in <b>Biotechnology</b>. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BScBT.aspx'>BSc - Biotechnology</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_msc_biotech.aspx'>MSc - Biotechnology</a></button> <br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/UG/UG_BTechBiotechnology.aspx'>B.Tech - Biotechnology</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/PG/PG_biotech.aspx'>M.Tech - Biotechnology</a></button> <br><br> In addition, if you like, type '<b>biotech-career</b>' and I'll be happy to tell you something about future career paths.",
                "<button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_bioinfo.aspx'>M.Tech - Bioinformatics</a></button> <br><br> By clicking on the button you're transferred to an overview over our Master in Bioinformatics. <br><br> Please type '<b> bioinf-career </b>' for corresponding future career paths.",

               "<button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechAgri.aspx'>B.Tech - Agri. Engineering</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BScAgri.aspx'>BSc - Agriculture</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2296'>MSc - Agriculture</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2295'>MBA - Agri Business</a></button> <br><br> I hope this helps. Each link gives you a good overview over the corresponding course. <br><br> Don't hesitate to ask if there is something else I can answer you.",
                
                "<button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2299'>BSc - Physics, Math. & Elective </a></button> <br> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/PG/PG_msc_maths.aspx'>MSc - Mathematics</a></button> <br> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2298'>MSc - Physics</a></button>  <br><br> I think these pages will help you. They give general information about our programs in Physics and Mathematics. <br><br> Tell me if there is something else I can help you with.",
                "Ah you're interested in our courses related to <b>Chemistry</b>. Then I recommend you to check out the pages below. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2013'>BSc - Biochemistry</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BScIC.aspx'>BSc - Industrial Chemistry</a></button> <br>  <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2071'>BSc - Zoology Botany & Chemistry</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=75'>MSc - Med. Biochemistry</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_msc_biochem.aspx'>MSc - Biochemistry</a></button>  <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BScIC.aspx'>MSc - Chemistry</a></button> ",
                "I think this general overview over our BSc in Life Science can be what you're looking for: <br><br><button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BScLifeSciences.aspx'>BSc - Life Sciences</a></button> ",
                "I think the pages below, containing general information about our programs in <b>Environmental Science</b>, can be what you're searching for. <br><br><button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=39'>BSc - Environmental S.</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=44'>MSc - Environmental S.</a></button> " ,

                "Sounds like you're interested in the field of <b>Architecture</b>.<br> To get all general information, I suggest you to visit the pages below. <br><br> For information about possible career paths please type '<b>arch-career<b/>' <br><br> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/UG/UG_BArch.aspx'>B.Arch</a></button>  <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=50'>M.Arch</a></button>", 
                "In the field of <b>Design</b>, we offer an undergraduate degree. Check the webpage below for general information about the same. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2300'>Bachelor of Design</a></button> <br><br> You want to know what career paths are waiting after graduation? Please type '<b>design-career<b/>' ",
                
                "I think I can help. These are links to pages for general information about each course we offer in the field of <b>Pharmacy </b>: <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BPharm.aspx'>Bachelor of Pharmacy</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2269'> M.Pharm - PC</a></button> <br><button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2163'>M.Pharm - Pharmaceutics</a></button> <br><button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2164'>M.Pharm - Pharmacology</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_pharma_d.aspx'>Pharm.D.</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2106'>Pharm.D. (Post Bac.)</a></button>  ",
                
                "I'm happy to hear you're interested in the field of <b>Commerce</b>. Check the pages below regarding general facts about our courses in this field. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2303'>Bachelor of Commerce</a></button>  <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2301'>Master of Commerce </a></button> <br><br> Type '<b>commerce-career</b>' and I'll give you information about career paths in this field.",
                "Okay. Check out the following pages for general information about our programs in Business Administration. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2302'>BBA</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/PG/PG_mba.aspx'>MBA </a></button> <br><br> Besides, for possible future career paths in this field just type '<b>business-career</b>'.",
                
                "Okay. I have this link with general information about our <b>M.B.B.S</b> for you. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=66'>M.B.B.S.</a></button>",
                "Sounds like you're interested in <b>Physiotherapy</b>.<br> To get all general information, I suggest you to visit the pages below. <br><br> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=68'> Bachelor of Physiotherapy (BPT)</a></button> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=72'>Master of Physiotherapy (MPT)</a></button>", 
                "Ah, in this field, we offer a Bachelor of Science degree. Check the webpage below for general information about the same. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=70'> BSc - Medical Laboratory Technology</a></button>",
                "In the field of <b>Optometry</b> we offer a Bachelor degree. Click on the button below for general facts about the same. <br><br> <button class = 'link__button' type='button'><a href='http://iul.ac.in/Program/ProgramDetails.aspx?page=2074'>Bachelor of Optometry</a></button> ",
                "I'm happy to hear you're interested in the field of <b>Radiology</b>. Check this page regarding general facts about our BSc. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=71'>BSc - Radiological Imaging Technology</a></button>",
                "Okay. Check out the following pages for general information about our BSC in <b>Forensic Science</b>. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2075'>BSc - Forensic Science</a></button>",
                "Okay. I think you should visit the following page. Here you get all general information about our Master in <b>Ophthalmology</b>. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2179'>Master of Surgery - Ophthalmology</a></button>",
                "Okay. I recommend you checking out the page below. It contains all general information about our Doctor of Medicine in <b>Pathology</b>.<br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2167'>Doctor in Pathology</a></button>",
                "Ah, I think I can help. Click ont the button below for general information about our Doctor of Medicine in <b>Anesthesiology</b>. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BTechME.aspx'>Dr in Anesthesiology</a></button> ",
                "Okay. I'm glad to hear you're interested in our Master of Surgergy in <b>Obstetrics and Gynaecology</b>. Let me give you all general information about the same: <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2178'> Obstetrics and Gynaecology Degree</a></button>",
                "Ah you're interested in <b>Anatomy</b>. <br> Then I recommend you to check out the following page. It gives you all general information about the correspponding course. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/PG/PG_msc_ma.aspx'>BSc - Medical Anatomy</a></button> ",
                "I'm happy to hear you're interested in the field of <b>Microbiology</b>. <br> Click on the following buttons for general facts about our Master degrees. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/PG/PG_msc_mb.aspx'>MSc - Microbiology</a></button> <br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/PG/PG_med_micro.aspx'>MSc - Med. Microbiology</a></button>",
                "Okay. I think I can help. Here are some general information about our MSc in <b>Medical Physiology</b>: <br><br>  <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/PG/PG_msc_mp.aspx'>MSc - Medical Physiology</a></button>",

                "Okay. I think you should visit one of the pages below. There you'll find all general facts about our courses in <b>Education</b>. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/UG/UG_BED.aspx'>Bachelor of Education</a></button> <button class = 'link__button' type= 'button'><a href='http://iul.ac.in/Program/PG/PG_education.aspx'>Master of Education</a></button> <br><br> In addition, when you type '<b>ed-career</b>', I'll tell you something about future career paths.",
                
                "First, I recommend you checking out the pages below to get general information about our programs in <b>English</b>. <br><br> Secondly, when you type '<b>english-career</b>', I tell you something about possible career paths in this field. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_BA_English.aspx'>BA - English</a></button> <br> <button class = 'link__button' type= 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=86'>MA - English</a></button>",
                "<button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2095'>BA - Economics</a></button> <br><br> I think this page with a general overview over our <b>Economics</b> degree can be what you're looking for. <br><br> Also I provide you facts about career paths in Economics if you type '<b>economics-career</b>'",
                "Ah you're interested in <b>political sciences</b>. Then I recommend you to check out the page below.  <br><br> For possible career paths in this field please type '<b>political-career</b>'. <br><br> <button class = 'link__button' type = 'button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2093'>BA - Political Science</a></button>",
                "<button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2089'>BA - Psychology</a></button> <br><br> I think this page can be what you're searching for. It contains all general information about the course.  <br><br> Also, if you type '<b>psych-career</b>' I'll tell you possible future carrer paths in this field." ,
                
                "Okay. I'm glad to hear you're interested in our programs in <b>Law</b>. Let me give you all general facts about them: <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=105'>BA - Law (B.A.LL.B)</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=104'>BBA - Law (BBA.LL.B)</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/UG/UG_LLB.aspx'>Bachelor of Law (LL.B)</a></button> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2118'>Master of Law (LL.M.)</a></button>",

                "I recommend you checking out the pages below. They give you all general facts about our <b>Nursing</b> degrees. <br><br> Apart from that, type <br> '<b>nurse-career</b>' <br> for information about possible career paths in this field. <br><br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=80'>BSc - Nursing (Basic)</a></button> <br> <button class = 'link__button' type='button'><a href='https://iul.ac.in/Program/ProgramDetails.aspx?page=2087'>BSc - Nursing (Post Basic)</a></button> ",           
                ]

career_paths_inputs =['biomed-career', 'mech-career', 'ee-career', 'ce-career', 'ca-career', 'cse-career','food-career', 'ece-career', 'biotech-career', 'bioinf-career', 'arch-career', 'design-career', 'commerce-career', 'business-career', 'ed-career', 'english-career', 'economics-career','political-career', 'psych-career','nurse-career']
career_paths_responses= [
                        "After studies in <b>Biomedical Engineering</b> one can become a Medical Technology Developer developping hardware and software for medical devices. Also as Rehabilitation Engineer you would be working with rehabilitation technology. Another example would be becoming a Biomaterials Developer, generating materials which repair or replace lost function to the body, or to detect and image diseases. And there are many more like Consultant, Manufacturing Engineer or Scientist. <br>The salary in this field ranges between ₹ 1.2 Lakhs to ₹ 6.0 Lakhs with an average annual salary of ₹ 3.0 Lakhs.<br><br> Don't hesitate to ask you next question. I'm happy to help.", 
                        "<b>Mechanical Engineering</b> deals with the design, development, installation, operation and maintenance of anything that has moving parts. Because of this, you'll find a placement in a range of sectors including: aerospace engineering, automotive engineering, construction, energy, manufacturing, medicine and railway engineering.<br> The average salary for a Mechanical Engineer in India is 3.2 Lakhs per year. <br><br> What else do you want to know?",
                        "An <b>Electrical Engineer</b> designs, develops and maintains the electrical control systems and components in for example automobiles, navigation systems or communication systems. He or she is hereby responsible for ensuring the smooth running of services such as lighting, heating, and ventilation. Besides, duties could also include working at heights or with power generating equipment. <br>The salary here ranges from INR 3 to 10 Lakhs p.a. <br><br> How can I assist you further?",
                        "You want to design, plan and contribute to construct your surrounding infrastructure? Obt for <b>Civil Engineering</b>. As a Construction Engineer for example you revise the construction plans, assign tasks to construction workers and evaluate the progress. On the contrary a Structural Engineer plans bridges, pipelines, viaducts, etc. and writes and draws construction documents. Also you check if the project meets environmental, safety, and legal guidelines. As Water Resource Engineer you would develop water infrastructure plans and evaluate potential problems using computer simulations.If you are more into transportation, you can also become a Transportation Planner and design solutions to problems like congestion, accessibility to highways, impact of new buildings and infrastructures of the transportation systems. <br> Depending on different factors, your annual salary could range from INR 229k to INR 1m <br><br> Tell me if there is something else you want to know",
                        "You want to design apps, want to code and think of software solutions that make the world better and more efficient? Obt for <b>Computer Applications</b>. Possible careers are for example Software Consultant, Hardware Engineer, Web Designer/Web Developer or Technical Consultant.<br> The IT industry is booming. Hence, in india the average salary is at Rs 7.96 Lakh per year <br><br> What else do you want to know?",
                        "Today, data and informatics increasingly gains importance and power in everydays life of everyone. <b>Computer Science and Engineering</b> is a perfect choice to be a part of the growth of this exciting branch. Social media, advertisement, sports, administration,... in every company and organisation there are well payed placements for Software Engineers, Information Security Manager, Data Analysts, Data Scientists, Computer Network Architects and Information Systems Managers. <br>The annual salary here ranges from INR 0.2 Lakhs to INR 25.0 <br><br> How can I assist you further?",
                        "<b>Food Technology</b> is a very versatile and fast growing branch with many placement opportunities. As Research Scientist you carry out various experiments using chemistry, microbiology, engineering, and other sciences that lead to improved yield, flavor, nutrition, and general acceptability of food. A Food Inspector/ Quality Controller on the contrary is the one who, by running tests, ensures that the quality of the produced food is maintained. Besides, a Biochemist recommends methods by which raw materials are converted into processed food, suggesting improvements in food quality, texture, flavor, storage, etc. An engineer in the food industry is the one who plans, designs and improves the processing systems. And there are many more.<br> Food Technologist salary in India ranges between ₹ 0.3 Lakhs to ₹ 7.6 Lakhs with an average annual salary of ₹ 3.0 Lakhs <br><br> What other Integral-related question can I answer you?",
                        "Graduating in <b>Electronics amd Communication Engineering</b> qualifies you for a variety of fascinating positions. Just to mention some of them: As electronics device and development engineer you come up with product ideas and develop actual products. As Communication engineer you manage and monitor the team's performance and budget, timeframes. Also you develop test procedures and plans for any disaster. A Telecommunication network engineer on the contrary examines the security, design and performance of computer networks and data transmission. Finally a Field Test Engineer creates electrical devices like radar, motors, and power generation equipment. They also create systems like broadcast systems, portable music and GPS. <br>Your salary hereby can range from INR 0.2 Lakhs per year to INR 12.0 Lakhs with an average annual salary of INR 2.2 Lakhs. <br><br> What other Integral-related question is on your mind?",
                        "The interdisciplinary course of <b>Biotechnology</b> prepares you to work as technician, analyst or scientist in a wide range of branches. Let me give you some examples: drug and pharmaceutical research industry, public funded laboratories, chemical, environment control, waste management, energy, food processing, clinical research and agriculture.<br> The salary can vary from INR 0.2 Lakhs to INR 4.6 Lakhs per year <br><br> What else do you want to know? ",
                        "Graduating in <b>Bioinformatics</b> qualifies you for varying positions like database programmer, computational biologist, network administrator, research scientist, bioinformatics software developer,... Graduates can also find a placement as for example Bioinformatics Analyst for conducting research, organizing data, maintaining databases and writing protocols. An other example is being a Bioinformatics technician who uses computers to analyze and track data related to biological functions and activities. The goal is to gain a better understanding of how complex biological processes work by analyzing DNA and the characteristics of cells. Biostatisticians on the contrary are analyzing environmental conditions and medical treatments on living organisms.<br> The salary in this broad field ranges from INR 3 lakhs to INR 10 lakhs per year <br><br> What else can I answer you?",
                        
                        "As a licenced architect you cannot only work as Architect. At the same time you can also opt for exciting positions as architectural technologist, interior and spatial designer, building surveyor, town planner or even historic buildings inspector. <br> With a masters degree the salary ranges from 4 lac to 16 lac per year <br> <br> What else do you want to know?",
                        "With your Bachelor of <b>Design</b> you can become for example interior designer, fashion designer, game designer, product designer, graphic designer, fashion consultant or even visual merchandiser.<br> Depending on your experience and branch of choice, the salary varies between INR 1.4 Lacs to INR 8.0 Lacs per year <br><br> Don't hesitate to formulate your next question. I'm happy to help.",
                        
                        "A degree in <b>Commerce</b> prepares you for very well payed and powerful professions. Earning an average salaray of INR 5.1 Lakh per year with potential up to INR 40 Lakh, commerce is a very promising career path. Skills in commerce are demanded in almost every branch you can think of. For example you can obt for a placement as Chartered Accountant, Marketing Manager, Investment Banker, Business Consultant, Human Resource Manager, Chartered Financial Analyst and many more. <br><br> How can I help you further?",
                        "Graduating in <b>Management</b> qualifies you for a variety of positions in every company you can think of. From Investment Manager, Change management engineer, Business Development Manage, Social Media Manager and Project Manager to Consultant, choose your branch and all doors are open to you.<br> Management skills will be well payed with an average salary of INR 12.0 Lakhs per year with a potential up to 80 Lakhs. <br><br> Is there another question I can help you with? Please ask.", 
                        
                        "After obtaining a <b>M.Ed</b> degree you can work as a teacher in senior secondary schools and high schools/secondary schools in both government and private schools. An M.Ed is mandatory to get employed as a post graduate teacher. After completing an M.Ed degree one can start working on multiple fields, teaching being the most common one.<br> The salary here ranges between INR 25K and INR 50K in the government sector and 20K to 40K per month in the private sector.  <br><br> Is there another question I can help you with? Please ask.",
                        
                        "With your MA in <b>English</b> you can work as Writer, Translator, Journalist. Also, you can get to work with an entrance examination coaching centre, tuition centre, private schools, spoken English coaching centre and more. Besides, a career as Corporate Communication Executive or Instructional Designer is possible. <br>The salary varies a loton the chosen career path, but the average in India is ₹418k per year. <br><br> What other Integral-related question is on your mind?", 
                        "After your BA in <b>Economics</b>, you can continue your studies in Commerce, Economics, Education and Business Administration. Also, you are qualified for jobs in Civil Services, Banks, Journalism and Human Reosurces. Job names could be for example Finance Budget Analyst, Market Analyst, Economist or Investment Administrator.<br> The average salary of a BA Economics graduate in India is ₹2,51,567 LPA. <br><br> How can I help you further?",
                        "The Bachelor in <b>Political Science</b> makes you qualified for Civil Services, maintaining the laws and morals among the citizens. Furthermore, as Public Relation Specialist you could work as a campaigner for governments, institutions, businesses, and companies for the promotion of products and policies to help them grow relations and popularity among the mass. Also you can pursue a career in journalism by choosing a Master’s Degree in Journalism and Mass Communication. Besides, by graduating in a Master's of Political Science you can become a political scientists and critically analyse the government policies. <br> The average salary of a BA Political Science graduate in India is ₹456,814 LPA. How can I assist you further?",
                        "With a BA in <b>Psychology</b> you can opt for jobs in health service, counseling, child daycare service, prisons, personnel administration, and research. Of course you can continue your studies with starting a Master's degree in a related field but starting to work is an option too. Jobs after BA Psychology include Career Counsellor, Child Psychologist, Developmental Psychologist, Social Psychologist, Community Health Officer, Social Worker, and Daycare Supervisor. <br> The average BA Psychology salary in India is INR 4.9 LPA. <br><br> Tell me if there is something else you want to know",

                        "The rapid growth and never ending demand of the medical sector, calls for more and more nurses. With a Bachelor in <b>Nursing</b> you can for example become Nursing Superintendent, Teacher of Nursing, Staff Nurse, Nursing Service Administrators, Military Nurse, Industrial Nurse, Community Health Nurse and more. The average BSC Nursing salary for a Staff Nurse ranges from ₹1.3 Lakhs to ₹ 3.1 Lakhs per year. <br><br> What else do you want to know?"
                     
                     ]